import { getSupabaseClient } from "./supabaseClient.js";
import { getJsonCompletion } from "./jsonCompletion.js";
import { buildPatternTranslationPrompt } from "./prompts.js";
import { getActiveLlmProvider, type LlmProvider } from "./llm.js";
import { resolveSyllabusScopeIds } from "./curriculumReconciliation.js";

// Sibling tool to topicTranslation.ts -- same root problem (Stage 1's own
// LANGUAGE fix and Curriculum reconciliation only touch
// archetype_question_signatures.signature.curriculum, never anything on
// the archetypes table itself), different field: the archetypes table's
// own archetype.name and archetype.student_explanation, generated by
// Stage 2 (the Miner) and the one-time student-explanation backfill --
// see prompts.ts's own LANGUAGE notes on both, added after this was
// found. Confirmed live: the student-facing "Practice a specific
// pattern" pill text for a West Bengal Board Grade 10 Life Science
// archetype was still in English ("Integrate pollution effects on
// health with conservation strategies") even though that same
// archetype's supporting questions' curriculum.chapter was already
// correctly reconciled to Bengali script.
//
// An archetype has no curriculum.chapter of its own -- that lives on its
// SUPPORTING QUESTIONS (archetype_question_signatures), one per member
// question. So eligibility here mirrors topicTranslation.ts's own fix for
// the same underlying trap (a real chapter can be Romanized, and an
// UNRESOLVED chapter gives no reliable script signal): resolve each
// archetype's own MODE chapter across its supporting questions (same
// modeOf() approach the orchestrator's own archetypeExercises.ts already
// uses to resolve a picker's own subTopic), and only translate an
// archetype whose mode chapter is a real, exact syllabus_topics value.
const PAGE_SIZE = 1000;

const NON_ASCII_RE = /[^\x00-\x7F]/;

function normalize(s: string): string {
  return s.trim().toLowerCase().normalize("NFC");
}

type ArchetypeRow = {
  run_id: string;
  archetype_id: string;
  archetype: {
    name?: string;
    student_explanation?: string | null;
    supporting_question_ids?: string[];
  };
};

async function loadArchetypeRows(params: { boardName: string; gradeName: string; subjectName: string }): Promise<ArchetypeRow[]> {
  const supabase = getSupabaseClient();
  const rows: ArchetypeRow[] = [];
  let offset = 0;
  for (;;) {
    const { data, error } = await supabase
      .from("archetypes")
      .select("run_id, archetype_id, archetype")
      .eq("education_context->curriculum_source->>name", params.boardName)
      .eq("education_context->>grade_or_year", params.gradeName)
      .eq("education_context->>subject_or_course", params.subjectName)
      .range(offset, offset + PAGE_SIZE - 1);
    if (error) {
      console.error("Pattern translation: failed to load archetypes:", error);
      break;
    }
    const page = (data ?? []) as ArchetypeRow[];
    rows.push(...page);
    if (page.length < PAGE_SIZE) break;
    offset += PAGE_SIZE;
  }
  return rows;
}

type SignatureChapterRow = { run_id: string; question_id: string; signature: { curriculum?: { chapter?: string } } };

// Same purpose as archetypeExercises.ts's own chapterByQuestion -- a
// run_id:question_id -> chapter lookup, built once per pass rather than
// per archetype, over every run this scope's archetypes actually span.
async function loadChapterByQuestion(runIds: string[]): Promise<Map<string, string>> {
  const supabase = getSupabaseClient();
  const map = new Map<string, string>();
  if (runIds.length === 0) return map;
  const { data, error } = await supabase
    .from("archetype_question_signatures")
    .select("run_id, question_id, signature")
    .in("run_id", runIds);
  if (error) {
    console.error("Pattern translation: failed to load question signatures for chapter lookup:", error);
    return map;
  }
  for (const row of (data ?? []) as SignatureChapterRow[]) {
    const chapter = row.signature?.curriculum?.chapter?.trim();
    if (chapter) map.set(`${row.run_id}:${row.question_id}`, chapter);
  }
  return map;
}

// Same modeOf() approach archetypeExercises.ts already uses to resolve a
// picker's own subTopic from an archetype's supporting questions --
// picks the most common chapter (normalized comparison, original casing
// preserved), null on an archetype with no resolvable chapter at all.
function modeChapter(chapters: string[]): string | null {
  if (chapters.length === 0) return null;
  const counts = new Map<string, { count: number; display: string }>();
  for (const c of chapters) {
    const key = normalize(c);
    const existing = counts.get(key);
    if (existing) existing.count += 1;
    else counts.set(key, { count: 1, display: c });
  }
  let best: { count: number; display: string } | null = null;
  for (const entry of counts.values()) {
    if (!best || entry.count > best.count) best = entry;
  }
  return best?.display ?? null;
}

// Same shape as topicTranslation.ts's own ScopeSyllabusContext -- see
// that file's own comment for why acceptableKeys/topicsByChapter/
// anyNonAsciiSample are each needed.
type ScopeSyllabusContext = {
  acceptableKeys: Set<string>;
  topicsByChapter: Map<string, string[]>;
  anyNonAsciiSample: string | null;
};

async function loadScopeSyllabusContext(params: {
  boardName: string;
  gradeName: string;
  subjectName: string;
}): Promise<ScopeSyllabusContext> {
  const supabase = getSupabaseClient();
  const ids = await resolveSyllabusScopeIds(supabase, params);
  if (!ids) return { acceptableKeys: new Set(), topicsByChapter: new Map(), anyNonAsciiSample: null };

  const { data, error } = await supabase
    .from("syllabus_topics")
    .select("chapter, topic")
    .eq("board_id", ids.boardId)
    .eq("grade_id", ids.gradeId)
    .eq("subject_id", ids.subjectId);
  if (error || !data) {
    if (error) console.error("Pattern translation: failed to load syllabus_topics:", error);
    return { acceptableKeys: new Set(), topicsByChapter: new Map(), anyNonAsciiSample: null };
  }

  const acceptableKeys = new Set<string>();
  const topicsByChapter = new Map<string, string[]>();
  let anyNonAsciiSample: string | null = null;
  for (const row of data as { chapter: string; topic: string }[]) {
    acceptableKeys.add(normalize(row.chapter));
    acceptableKeys.add(normalize(row.topic));
    if (NON_ASCII_RE.test(row.topic)) {
      const key = normalize(row.chapter);
      const list = topicsByChapter.get(key) ?? [];
      if (!list.includes(row.topic)) list.push(row.topic);
      topicsByChapter.set(key, list);
      anyNonAsciiSample ??= row.topic;
    }
    if (NON_ASCII_RE.test(row.chapter)) anyNonAsciiSample ??= row.chapter;
  }
  return { acceptableKeys, topicsByChapter, anyNonAsciiSample };
}

// name/studentExplanation are null when that field doesn't need
// translating (already non-ASCII, or absent) -- an archetype only
// appears here at all when AT LEAST ONE of the two needs it.
type TranslatablePattern = {
  runId: string;
  archetypeId: string;
  name: string | null;
  studentExplanation: string | null;
  chapter: string;
  scriptExample: string;
};

async function computeTranslatable(rows: ArchetypeRow[], ctx: ScopeSyllabusContext): Promise<TranslatablePattern[]> {
  if (!ctx.anyNonAsciiSample) return [];

  const runIds = Array.from(new Set(rows.map((r) => r.run_id)));
  const chapterByQuestion = await loadChapterByQuestion(runIds);

  const translatable: TranslatablePattern[] = [];
  for (const row of rows) {
    const name = row.archetype.name?.trim();
    const studentExplanation = row.archetype.student_explanation?.trim();
    const nameNeedsTranslation = Boolean(name) && !NON_ASCII_RE.test(name!);
    const explanationNeedsTranslation = Boolean(studentExplanation) && !NON_ASCII_RE.test(studentExplanation!);
    if (!nameNeedsTranslation && !explanationNeedsTranslation) continue;

    const supportingChapters = (row.archetype.supporting_question_ids ?? [])
      .map((qid) => chapterByQuestion.get(`${row.run_id}:${qid}`))
      .filter((c): c is string => Boolean(c));
    const chapter = modeChapter(supportingChapters);
    if (!chapter || !ctx.acceptableKeys.has(normalize(chapter))) continue;

    const sameChapterTopics = ctx.topicsByChapter.get(normalize(chapter)) ?? [];
    const scriptExample = NON_ASCII_RE.test(chapter) ? chapter : (sameChapterTopics[0] ?? ctx.anyNonAsciiSample);

    translatable.push({
      runId: row.run_id,
      archetypeId: row.archetype_id,
      name: nameNeedsTranslation ? name! : null,
      studentExplanation: explanationNeedsTranslation ? studentExplanation! : null,
      chapter,
      scriptExample,
    });
  }
  return translatable;
}

export type PatternTranslationPreview = {
  translatablePatterns: number;
};

// Counts only -- no LLM call, no writes.
export async function previewPatternTranslation(params: {
  boardName: string;
  gradeName: string;
  subjectName: string;
}): Promise<PatternTranslationPreview> {
  const [rows, ctx] = await Promise.all([loadArchetypeRows(params), loadScopeSyllabusContext(params)]);
  const translatable = await computeTranslatable(rows, ctx);
  return { translatablePatterns: translatable.length };
}

type Translation = { runId: string; archetypeId: string; translatedName: string | null; translatedExplanation: string | null };

const MAX_TOKENS = 8000;

// Same reasoning as topicTranslation.ts's own BATCH_SIZE -- bounding each
// call's own output keeps this safe regardless of how large a scope's
// translatable-pattern set grows to. Lower than that file's 40 since each
// item here can carry TWO fields to translate (name AND
// student_explanation, the latter several sentences long) instead of one
// short topic label.
const BATCH_SIZE = 20;

function chunk<T>(items: T[], size: number): T[][] {
  const batches: T[][] = [];
  for (let i = 0; i < items.length; i += size) batches.push(items.slice(i, i + size));
  return batches;
}

async function requestTranslations(batch: TranslatablePattern[], provider: LlmProvider): Promise<Translation[]> {
  const { data } = await getJsonCompletion({
    systemPrompt: buildPatternTranslationPrompt(),
    message: JSON.stringify({
      patterns: batch.map((p) => ({
        archetype_id: p.archetypeId,
        name: p.name,
        student_explanation: p.studentExplanation,
        chapter: p.chapter,
        script_example: p.scriptExample,
      })),
    }),
    maxTokens: MAX_TOKENS,
    provider,
  });

  if (!Array.isArray(data)) {
    console.warn("Pattern translation: response was not a JSON array.");
    return [];
  }

  // archetype_id alone isn't a stable key across the WHOLE scope (the
  // same short slug can be reused by different mining runs -- see
  // pipelineRunner.ts's own renameCollidingArchetypeIds for the sibling
  // problem this already caused once for inserts); run_id:archetype_id
  // is what's actually unique, so responses are matched back to their
  // batch item that way, not by archetype_id alone.
  const byArchetypeId = new Map(batch.map((p) => [p.archetypeId, p]));
  const translations: Translation[] = [];
  let rejectedCount = 0;
  for (const item of data) {
    if (typeof item !== "object" || item === null) continue;
    const m = item as Record<string, unknown>;
    if (typeof m.archetype_id !== "string") continue;
    const source = byArchetypeId.get(m.archetype_id);
    if (!source) continue;

    const translatedName = typeof m.translated_name === "string" ? m.translated_name : null;
    const translatedExplanation = typeof m.translated_student_explanation === "string" ? m.translated_student_explanation : null;

    // Only accept a translation for a field this item actually asked for
    // (source.name/studentExplanation non-null), and only when it's
    // genuinely non-ASCII -- otherwise the model echoed the original (or
    // invented a field nobody asked for) rather than declining silently.
    const acceptedName = source.name && translatedName && NON_ASCII_RE.test(translatedName) ? translatedName : null;
    const acceptedExplanation =
      source.studentExplanation && translatedExplanation && NON_ASCII_RE.test(translatedExplanation) ? translatedExplanation : null;

    if (source.name && !acceptedName) rejectedCount++;
    if (source.studentExplanation && !acceptedExplanation) rejectedCount++;
    if (!acceptedName && !acceptedExplanation) continue;

    translations.push({
      runId: source.runId,
      archetypeId: source.archetypeId,
      translatedName: acceptedName,
      translatedExplanation: acceptedExplanation,
    });
  }
  console.log(
    `Pattern translation: model translated ${translations.length}/${batch.length} pattern(s), ${rejectedCount} field(s) rejected (not an actual translation).`
  );
  return translations;
}

// Rewrites archetype.name and/or archetype.student_explanation (ONLY --
// every other field on the archetype, including its supporting questions'
// own curriculum.chapter, is left exactly as it already was) for one
// archetype row.
async function applyTranslation(
  supabase: ReturnType<typeof getSupabaseClient>,
  translation: Translation
): Promise<boolean> {
  const { data, error } = await supabase
    .from("archetypes")
    .select("archetype")
    .eq("run_id", translation.runId)
    .eq("archetype_id", translation.archetypeId)
    .maybeSingle();
  if (error || !data) {
    console.error(`Pattern translation: failed to load archetype ${translation.runId}:${translation.archetypeId}:`, error);
    return false;
  }

  const current = data.archetype as Record<string, unknown>;
  const next = {
    ...current,
    ...(translation.translatedName ? { name: translation.translatedName } : {}),
    ...(translation.translatedExplanation ? { student_explanation: translation.translatedExplanation } : {}),
  };
  const { error: updateError } = await supabase
    .from("archetypes")
    .update({ archetype: next })
    .eq("run_id", translation.runId)
    .eq("archetype_id", translation.archetypeId);
  if (updateError) {
    console.error(`Pattern translation: failed to update archetype ${translation.runId}:${translation.archetypeId}:`, updateError);
    return false;
  }
  return true;
}

export type PatternTranslationResult = {
  translated: number;
  untranslatedRemaining: number;
};

let translationInProgress = false;

export function isPatternTranslationInProgress(): boolean {
  return translationInProgress;
}

// Same repeat-until-converged shape as topicTranslation.ts's own
// MAX_ITERATIONS.
const MAX_ITERATIONS = 5;

async function runPatternTranslationOnePass(params: {
  boardName: string;
  gradeName: string;
  subjectName: string;
}): Promise<PatternTranslationResult> {
  const supabase = getSupabaseClient();
  const [rows, ctx] = await Promise.all([loadArchetypeRows(params), loadScopeSyllabusContext(params)]);
  const translatable = await computeTranslatable(rows, ctx);

  if (translatable.length === 0) {
    return { translated: 0, untranslatedRemaining: 0 };
  }

  const provider = getActiveLlmProvider();
  const translations: Translation[] = [];
  for (const batch of chunk(translatable, BATCH_SIZE)) {
    try {
      translations.push(...(await requestTranslations(batch, provider)));
    } catch (err) {
      // One batch failing shouldn't take the rest of this pass's batches
      // down with it -- same reasoning topicTranslation.ts's own
      // per-batch try/catch already applies.
      console.error(`Pattern translation: batch of ${batch.length} pattern(s) failed:`, err);
    }
  }

  let translatedCount = 0;
  for (const translation of translations) {
    if (await applyTranslation(supabase, translation)) translatedCount++;
  }

  return { translated: translatedCount, untranslatedRemaining: translatable.length - translatedCount };
}

export async function runPatternTranslation(params: {
  boardName: string;
  gradeName: string;
  subjectName: string;
}): Promise<PatternTranslationResult> {
  if (translationInProgress) {
    throw new Error("A pattern translation pass is already in progress -- wait for it to finish before starting another.");
  }
  translationInProgress = true;
  try {
    const total: PatternTranslationResult = { translated: 0, untranslatedRemaining: 0 };
    for (let iteration = 1; iteration <= MAX_ITERATIONS; iteration++) {
      const pass = await runPatternTranslationOnePass(params);
      total.translated += pass.translated;
      total.untranslatedRemaining = pass.untranslatedRemaining;

      console.log(
        `Pattern translation: iteration ${iteration}/${MAX_ITERATIONS} for ${params.subjectName} (${params.boardName}, ` +
          `grade ${params.gradeName}) -- ${pass.translated} pattern(s) translated, ${pass.untranslatedRemaining} still untranslated.`
      );

      if (pass.translated === 0) break;
    }

    console.log(
      `Pattern translation: done -- ${total.translated} total pattern(s) translated, ${total.untranslatedRemaining} left untranslated.`
    );

    return total;
  } finally {
    translationInProgress = false;
  }
}
